### ISSUE TITLE
Odd state after failure to add proxy server

### ISSUE THREAD

**Issue by jpevarnek** [uProxy/ufo-management-server-flask#125]
Repro
-----
0. Do not set up server
0. Go to /setup and try to add a proxy server

Expected
----------
Don't even get the chance to add the server, should probably only show the setup fields (and at the top of the screen)

Actual
-----
Adding server fails, private key remains pasted in but all other values are cleared

**Comment by jpevarnek** [comment]
Note: If things succeed, the end result is having the private key left in the field and everything disappearing with no confirmation that the server got added

**Comment by xwsxethan** [comment]
Hmmm I know there's an issue with the edit server flow that seems to cause the page to freeze, but I haven't seen it on the ads flow yet. Are you using the latest vulcanized HTML? Also, which release was this on or locally?

**Comment by jpevarnek** [comment]
Screenshot from after successfully adding a server (note: no confirmation):
![screenshot-latest](https://cloud.githubusercontent.com/assets/902894/14641932/6cdb9ea6-0616-11e6-8be5-6c019c7f192e.png)

**Comment by xwsxethan** [comment]
I don't see this happening on http://ufo-nightly.herokuapp.com/setup/ (which should be the latest version of master). I've attempted with no servers setup and with adding an additional one, but both succeed and clear the field as expected.

**Comment by jpevarnek** [comment]
Okay, turns out this is a bug in an old version of iron-form.  Our bower dependency made that version sufficient for some reason.  Anyways, closing this.
