### ISSUE TITLE
Enter key does nothing in login

### ISSUE THREAD

**Issue by jpevarnek** [uProxy/ufo-management-server-flask#126]
Repro
-----
0. Fill in login form
0. Press enter

Expected
------
User is logged in

Actual
--------
Nothing happens

**Comment by xwsxethan** [comment]
Where did you attempt this, as in locally, on ufo-nightly, or on ufo-prod? If locally, you need the latest code and to run vulcanize.sh. If nightly, it should work. Prod doesn't have the PR so this is expected until an updated release.

**Comment by jpevarnek** [comment]
Ah, awesome, looks like I forgot to do a pull there.  Closing.
